### ISSUE TITLE
Bluetooth not working on 2012 MBP

### ISSUE THREAD

**Issue by AEAEAEAE4343** [dortania/OpenCore-Legacy-Patcher#841]
### Machine Model

MacBookPro9,1

### Application Version

Latest Release

### Application Variant

GUI (Graphical User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

Bluetooth cannot be enabled after updating to macOS 12. On BigSur, Bluetooth was working without any problems. I tried killing bluetoothd and BlueTool, with no succes. 

Note: there was a similar issue, #654, but that was with the AirPort Extreme card, this is with the stock one.

### Any Additional Information

System Profiler shows this under Bluetooth:
```
  Bluetooth-controller:
  Adres:			NULL
  Status:			Uit
  Chipset:			BCM_4350C2
  Detecteerbaar:		Uit
  Firmwareversie:		v0 c0
  Productcode:			0x0001
  Ondersteunde apparaten:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  Transport:			USB
  Fabrikantcode:		0x004C (Apple)
```

And this under USB:
![Image](https://i.imgur.com/3irMu03.png)
